from enum import Enum, IntEnum


class RealtimeEventType(str, Enum):
    """客户端可以接收的统一实时事件类型。"""

    SNAPSHOT = "SNAPSHOT"
    SUBSCRIBED = "SUBSCRIBED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_UPDATED = "ORDER_UPDATED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    TRADE_CREATED = "TRADE_CREATED"
    POSITION_UPDATED = "POSITION_UPDATED"
    POSITION_CLOSED = "POSITION_CLOSED"
    ACCOUNT_UPDATED = "ACCOUNT_UPDATED"
    PNL_UPDATED = "PNL_UPDATED"
    OPTION_VALUATION_UPDATED = "OPTION_VALUATION_UPDATED"
    RISK_STATE_CHANGED = "RISK_STATE_CHANGED"
    RESYNC_REQUIRED = "RESYNC_REQUIRED"
    AUTH_EXPIRED = "AUTH_EXPIRED"
    ERROR = "ERROR"
    HEARTBEAT = "HEARTBEAT"


class WebSocketCloseCode(IntEnum):
    """应用使用的私有关闭码，便于测试页面判断重连原因。"""

    NORMAL = 1000
    GATEWAY_SHUTDOWN = 1012
    AUTHENTICATION_FAILED = 4401
    PERMISSION_DENIED = 4403
    AUTH_EXPIRED = 4408
    LIMIT_EXCEEDED = 4429
    HEARTBEAT_TIMEOUT = 4450
    SLOW_CONNECTION = 4451
    RESYNC_REQUIRED = 4452
    SERVICE_UNAVAILABLE = 4503
