from enum import StrEnum


class CorporateActionStatus(StrEnum):
    DRAFT = "DRAFT"
    CONFIRMED = "CONFIRMED"
    ENTITLEMENT_CAPTURED = "ENTITLEMENT_CAPTURED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class CorporateActionComponentType(StrEnum):
    CASH_DIVIDEND = "CASH_DIVIDEND"
    STOCK_DIVIDEND = "STOCK_DIVIDEND"
    CAPITALIZATION_ISSUE = "CAPITALIZATION_ISSUE"
    RIGHTS_ISSUE = "RIGHTS_ISSUE"
    STOCK_SPLIT = "STOCK_SPLIT"
    REVERSE_SPLIT = "REVERSE_SPLIT"
    BOND_COUPON = "BOND_COUPON"
    BOND_MATURITY_REDEMPTION = "BOND_MATURITY_REDEMPTION"


class CorporateActionEntitlementStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    SUBSCRIBED = "SUBSCRIBED"
    PARTIALLY_SUBSCRIBED = "PARTIALLY_SUBSCRIBED"
    CREDITED = "CREDITED"
    PAID = "PAID"
    EXPIRED = "EXPIRED"
    REVERSED = "REVERSED"
    FAILED = "FAILED"
